# params.yaml
data_ingestion:
  test_size: 0.25
  data_path_url: 'https://raw.githubusercontent.com/vikashishere/Datasets/refs/heads/main/data.csv'
  data_path: './data'

feature_engineering:
  max_features: 50